- Updated realvec.h by adding "#include <cstring>" to the realvec header file so the following error concerning the "memcpy" function can be fixed:
  marsyas/src/marsyas/realvec.cpp: In member function ‘Marsyas::realvec& Marsyas::realvec::operator=(const Marsyas::realvec&)’:
  marsyas/src/marsyas/realvec.cpp:103: error: ‘memcpy’ was not declared in this scope



git-svn-id: svn+ssh://svn.code.sf.net/p/marsyas/code/trunk@4149 0e98fd9d-079e-457f-9c5c-d482923f975d